name: Shellcheck

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck.
      run: |
        git submodule update --remote --init -f
        shopt -s nullglob
        shellcheck */*/build */*/post-install
